//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSUploader.LangResx {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWSUploader.LangResx.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ≡ 조회 결과 - {0:n0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_UploadHistory {
            get {
                return ResourceManager.GetString("count_UploadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   맑은 고딕과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업로드 취소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_CancleUpload {
            get {
                return ResourceManager.GetString("msg_CancleUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류가 발생하여 암호를 변경하지 못했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ChangeError {
            get {
                return ResourceManager.GetString("msg_ChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암호가 정상적으로 변경되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ChangePW {
            get {
                return ResourceManager.GetString("msg_ChangePW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 암호와 암호확인 암호가 다릅니다.
        ///다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ChangePWError {
            get {
                return ResourceManager.GetString("msg_ChangePWError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 암호를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ChangePWNull {
            get {
                return ResourceManager.GetString("msg_ChangePWNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀데이터 생성 및 검사중입니다….과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_CreateData {
            get {
                return ResourceManager.GetString("msg_CreateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀데이터를 생성하지 못했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_CreateDataError {
            get {
                return ResourceManager.GetString("msg_CreateDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_CRUDError {
            get {
                return ResourceManager.GetString("msg_CRUDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1900-01-01 데이터 {0}건 존재!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_DateError {
            get {
                return ResourceManager.GetString("msg_DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 파일에 데이터가 비어있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_EmptyFile {
            get {
                return ResourceManager.GetString("msg_EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암호를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_EmptyPW {
            get {
                return ResourceManager.GetString("msg_EmptyPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀파일을 닫으신 후에 다시 시도해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ExcelError {
            get {
                return ResourceManager.GetString("msg_ExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복데이터 {0:n0}건 존재!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ExistData1 {
            get {
                return ResourceManager.GetString("msg_ExistData1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 업로드된 데이터가 {0:n0}건 존재합니다
        ///새로 발생한(중복분 제외) 데이터만 업로드 할까요?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ExistData2 {
            get {
                return ResourceManager.GetString("msg_ExistData2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정상적인 융착정보 엑셀파일이 아닙니다!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_FileError {
            get {
                return ResourceManager.GetString("msg_FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}은 정해진 형식의 엑셀파일이 아닙니다. 확인 후 다시 시도해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_FileFormatError {
            get {
                return ResourceManager.GetString("msg_FileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] 파일 불러오기 완료!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_FileLoad1 {
            get {
                return ResourceManager.GetString("msg_FileLoad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Upload 버튼으로 업로드를 시작하세요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_FileLoad2 {
            get {
                return ResourceManager.GetString("msg_FileLoad2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [오류] 선택하신 csv파일을 읽어오지 못했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_FileLoadError {
            get {
                return ResourceManager.GetString("msg_FileLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   첫 로그인 시 비밀번호 변경이 필요합니다.
        ///비밀번호 변경 후 이용해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_FirstLogin {
            get {
                return ResourceManager.GetString("msg_FirstLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}:{1}] 폴더 오류: {2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_FolderError {
            get {
                return ResourceManager.GetString("msg_FolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   존재하지 않는 UserID입니다.
        ///올바른 ID를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_IDError {
            get {
                return ResourceManager.GetString("msg_IDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 중복 확인중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_isExistData {
            get {
                return ResourceManager.GetString("msg_isExistData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검수목록이 들어있는 [{0}] 폴더를 불러오시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_LoadBeadFile {
            get {
                return ResourceManager.GetString("msg_LoadBeadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀파일을 불러오고 있습니다….과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_LoadFile {
            get {
                return ResourceManager.GetString("msg_LoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   융착정보 엑셀파일을 읽어오지 못했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_LoadFileError {
            get {
                return ResourceManager.GetString("msg_LoadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버에 접속할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_LoginError1 {
            get {
                return ResourceManager.GetString("msg_LoginError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB Connection에 문제가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_LoginError2 {
            get {
                return ResourceManager.GetString("msg_LoginError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 암호가 다릅니다.
        ///
        ///정확한 암호를 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_NowPWError {
            get {
                return ResourceManager.GetString("msg_NowPWError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 암호를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_NowPWNull {
            get {
                return ResourceManager.GetString("msg_NowPWNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   분석대상 CSV 파일이 들어있는 폴더를 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_NullBeadFile {
            get {
                return ResourceManager.GetString("msg_NullBeadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   업로드할 융착정보 엑셀파일을 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_NullWeldFile {
            get {
                return ResourceManager.GetString("msg_NullWeldFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암호가 다릅니다.
        ///
        ///정확한 암호를 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_PWError {
            get {
                return ResourceManager.GetString("msg_PWError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암호확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_ChangePWError {
            get {
                return ResourceManager.GetString("msg_title_ChangePWError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경암호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_ChangePWNull {
            get {
                return ResourceManager.GetString("msg_title_ChangePWNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_Exist {
            get {
                return ResourceManager.GetString("msg_title_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복 확인 불가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_ExistDataError {
            get {
                return ResourceManager.GetString("msg_title_ExistDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재암호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_NowPWNull {
            get {
                return ResourceManager.GetString("msg_title_NowPWNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원장생성오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_UploadError {
            get {
                return ResourceManager.GetString("msg_title_UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 업로드를 시작하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_UploadData {
            get {
                return ResourceManager.GetString("msg_UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   대상목록을 업로드 할 수 없습니다. 확인 후 다시 실행해 주세요. {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_UploadError {
            get {
                return ResourceManager.GetString("msg_UploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}:{1}] 업로드 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_UploadFail {
            get {
                return ResourceManager.GetString("msg_UploadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 전송중이니 완료시까지 기다려주세요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_Uploading {
            get {
                return ResourceManager.GetString("msg_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}:{1}] 업로드 완료!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_UploadSuccess {
            get {
                return ResourceManager.GetString("msg_UploadSuccess", resourceCulture);
            }
        }
    }
}
