//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWSAnalyzer.LangResx {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SWSAnalyzer.LangResx.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   전체보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btn_viewall {
            get {
                return ResourceManager.GetString("btn_viewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   간략보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btn_viewsummary {
            get {
                return ResourceManager.GetString("btn_viewsummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭    제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   수    정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnModify {
            get {
                return ResourceManager.GetString("btnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   신    규과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnNew {
            get {
                return ResourceManager.GetString("btnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≡ 상세 정보 - {0:n0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_BeadDetail {
            get {
                return ResourceManager.GetString("count_BeadDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≡ 검수데이터 목록 - {0:n0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_BeadMaster {
            get {
                return ResourceManager.GetString("count_BeadMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≡ 검수+융착 데이터 목록 - {0:n0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_BeadWeld {
            get {
                return ResourceManager.GetString("count_BeadWeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≡ 회사 목록 - {0:n0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_Comp {
            get {
                return ResourceManager.GetString("count_Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≡ 검수 데이터 - {0:n0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_General {
            get {
                return ResourceManager.GetString("count_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≡ {0} 프로젝트 목록 - {1:n0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_Project {
            get {
                return ResourceManager.GetString("count_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≡ {0} 사용자 목록 - {1:n0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_User {
            get {
                return ResourceManager.GetString("count_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≡ 융착데이터 목록 - {0:n0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string count_WeldMaster {
            get {
                return ResourceManager.GetString("count_WeldMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검수상세정보과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string excel_BeadDetail {
            get {
                return ResourceManager.GetString("excel_BeadDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검수데이터목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string excel_BeadMaster {
            get {
                return ResourceManager.GetString("excel_BeadMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검수+융착 데이터 목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string excel_BeadWeld {
            get {
                return ResourceManager.GetString("excel_BeadWeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   검수마스터_{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string excel_PopBeadMaster {
            get {
                return ResourceManager.GetString("excel_PopBeadMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   융착마스터_{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string excel_PopWeldMaster {
            get {
                return ResourceManager.GetString("excel_PopWeldMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 조직도과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string excel_ProjRealation {
            get {
                return ResourceManager.GetString("excel_ProjRealation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   융착데이터목록과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string excel_WeldMaster {
            get {
                return ResourceManager.GetString("excel_WeldMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   맑은 고딕과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Properties.Resources.Dashboard2KR과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string img_Dashboard2 {
            get {
                return ResourceManager.GetString("img_Dashboard2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상위 Admin을 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_AdminNull {
            get {
                return ResourceManager.GetString("msg_AdminNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] 내 [Admin] 권한이 이미 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_AuthExist1 {
            get {
                return ResourceManager.GetString("msg_AuthExist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] 내 [{1}] 권한이 이미 존재합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_AuthExist2 {
            get {
                return ResourceManager.GetString("msg_AuthExist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   권한등급을 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_AuthLevelNull {
            get {
                return ResourceManager.GetString("msg_AuthLevelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체기간을 검색하는 경우는 SerialNo 또는 Material 조건값이 하나라도 있어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_BeadSearchAll {
            get {
                return ResourceManager.GetString("msg_BeadSearchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체기간을 검색하는 경우 Machine SerialNo, Material, Serial 조건값이 하나라도 있어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_BeadWeldSearchAll {
            get {
                return ResourceManager.GetString("msg_BeadWeldSearchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   오류가 발생하여 암호를 변경하지 못했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ChangeError {
            get {
                return ResourceManager.GetString("msg_ChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암호가 정상적으로 변경되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ChangePW {
            get {
                return ResourceManager.GetString("msg_ChangePW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 암호와 암호확인 암호가 다릅니다.
        ///다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ChangePWError {
            get {
                return ResourceManager.GetString("msg_ChangePWError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경할 암호를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ChangePWNull {
            get {
                return ResourceManager.GetString("msg_ChangePWNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스킨 변경시 프로그램 재시작이 필요합니다.
        ///재시작하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ChangeSkin {
            get {
                return ResourceManager.GetString("msg_ChangeSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회사를 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_CompanyNull {
            get {
                return ResourceManager.GetString("msg_CompanyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 존재하는 업체명입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_CompExist {
            get {
                return ResourceManager.GetString("msg_CompExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회사명을 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_CompNull {
            get {
                return ResourceManager.GetString("msg_CompNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   저장 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_CRUDError {
            get {
                return ResourceManager.GetString("msg_CRUDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정말 삭제하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_Del {
            get {
                return ResourceManager.GetString("msg_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암호를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_EmptyPW {
            get {
                return ResourceManager.GetString("msg_EmptyPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   엑셀파일을 닫으신 후에 다시 시도해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ExcelError {
            get {
                return ResourceManager.GetString("msg_ExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   만료일자를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ExpireNull {
            get {
                return ResourceManager.GetString("msg_ExpireNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   첫 로그인 시 비밀번호 변경이 필요합니다.
        ///비밀번호 변경 후 이용해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_FirstLogin {
            get {
                return ResourceManager.GetString("msg_FirstLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   존재하지 않는 UserID입니다.
        ///올바른 ID를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_IDError {
            get {
                return ResourceManager.GetString("msg_IDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버에 접속할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_LoginError1 {
            get {
                return ResourceManager.GetString("msg_LoginError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB Connection에 문제가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_LoginError2 {
            get {
                return ResourceManager.GetString("msg_LoginError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상위 Manager를 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ManagerNull {
            get {
                return ResourceManager.GetString("msg_ManagerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택하신 {0}건의 데이터를 삭제하시겠습니까?
        ///삭제하시면 하위 상세데이터까지 모두 삭제됩니다(복구불가)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_MasterDel1 {
            get {
                return ResourceManager.GetString("msg_MasterDel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터를 삭제하는 중입니다.  잠시 기다려주세요….과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_MasterDel2 {
            get {
                return ResourceManager.GetString("msg_MasterDel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성공적으로 삭제되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_MasterDel3 {
            get {
                return ResourceManager.GetString("msg_MasterDel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제시 오류가 발생했습니다. 재조회하여 삭제여부를 확인해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_MasterDelError {
            get {
                return ResourceManager.GetString("msg_MasterDelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택하신 [{0}]의 융착데이터({1})를 [{2}]의 [{3}]로 관리권한을 변경하시겠습니까?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_MasterTransfer1 {
            get {
                return ResourceManager.GetString("msg_MasterTransfer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터를 변경하는 중입니다.  잠시 기다려 주세요...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_MasterTransfer2 {
            get {
                return ResourceManager.GetString("msg_MasterTransfer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   성공적으로 변경되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_MasterTransfer3 {
            get {
                return ResourceManager.GetString("msg_MasterTransfer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경시 오류가 발생했습니다. 재조회하여 변경여부를 확인해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_MasterTransferError {
            get {
                return ResourceManager.GetString("msg_MasterTransferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 암호가 다릅니다.
        ///
        ///정확한 암호를 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_NowPWError {
            get {
                return ResourceManager.GetString("msg_NowPWError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재 암호를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_NowPWNull {
            get {
                return ResourceManager.GetString("msg_NowPWNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조회할 데이터가 없습니다.
        ///
        ///확인 후 다시 실행해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_PopDataEmpty {
            get {
                return ResourceManager.GetString("msg_PopDataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트를 선택해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ProjectNull {
            get {
                return ResourceManager.GetString("msg_ProjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 존재하는 프로젝트명입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ProjExist {
            get {
                return ResourceManager.GetString("msg_ProjExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트명을 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_ProjNull {
            get {
                return ResourceManager.GetString("msg_ProjNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암호가 다릅니다.
        ///
        ///정확한 암호를 다시 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_PWError {
            get {
                return ResourceManager.GetString("msg_PWError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상위 Admin과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_AdminNull {
            get {
                return ResourceManager.GetString("msg_title_AdminNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   권한 존재과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_AuthExist {
            get {
                return ResourceManager.GetString("msg_title_AuthExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   권한등급과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_AuthLevelNull {
            get {
                return ResourceManager.GetString("msg_title_AuthLevelNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   암호확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_ChangePWError {
            get {
                return ResourceManager.GetString("msg_title_ChangePWError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경암호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_ChangePWNull {
            get {
                return ResourceManager.GetString("msg_title_ChangePWNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회사과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_CompanyNull {
            get {
                return ResourceManager.GetString("msg_title_CompanyNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회사명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_CompNull {
            get {
                return ResourceManager.GetString("msg_title_CompNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_Del {
            get {
                return ResourceManager.GetString("msg_title_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   중복과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_Exist {
            get {
                return ResourceManager.GetString("msg_title_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   만료일자과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_ExpireNull {
            get {
                return ResourceManager.GetString("msg_title_ExpireNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상위 Manager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_ManagerNull {
            get {
                return ResourceManager.GetString("msg_title_ManagerNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_MasterTransfer {
            get {
                return ResourceManager.GetString("msg_title_MasterTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   현재암호과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_NowPWNull {
            get {
                return ResourceManager.GetString("msg_title_NowPWNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   데이터 없음과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_PopDataEmpty {
            get {
                return ResourceManager.GetString("msg_title_PopDataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_ProjectNull {
            get {
                return ResourceManager.GetString("msg_title_ProjectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_ProjNull {
            get {
                return ResourceManager.GetString("msg_title_ProjNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조건필요과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_SearchAll {
            get {
                return ResourceManager.GetString("msg_title_SearchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_title_UserIDNull {
            get {
                return ResourceManager.GetString("msg_title_UserIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   하위 계정이 존재합니다.
        ///하위 계정 삭제 후 다시 시도해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_UserDelError {
            get {
                return ResourceManager.GetString("msg_UserDelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_UserIDNull {
            get {
                return ResourceManager.GetString("msg_UserIDNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자명을 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_UserNameNull {
            get {
                return ResourceManager.GetString("msg_UserNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 암호를 입력해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_UserPWNull {
            get {
                return ResourceManager.GetString("msg_UserPWNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전체기간을 검색하는 경우 Machine SerialNo, Material, Diameter 조건값이 하나라도 있어야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string msg_WeldSearchAll {
            get {
                return ResourceManager.GetString("msg_WeldSearchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회사 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title_CompDel {
            get {
                return ResourceManager.GetString("title_CompDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회사 수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title_CompMod {
            get {
                return ResourceManager.GetString("title_CompMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   회사 신규과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title_CompNew {
            get {
                return ResourceManager.GetString("title_CompNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title_ProjDel {
            get {
                return ResourceManager.GetString("title_ProjDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title_ProjMod {
            get {
                return ResourceManager.GetString("title_ProjMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로젝트 신규과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title_ProjNew {
            get {
                return ResourceManager.GetString("title_ProjNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 삭제과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title_UserDel {
            get {
                return ResourceManager.GetString("title_UserDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 수정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title_UserMod {
            get {
                return ResourceManager.GetString("title_UserMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용자 신규과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string title_UserNew {
            get {
                return ResourceManager.GetString("title_UserNew", resourceCulture);
            }
        }
    }
}
